the fix for the search is bom (#38)
* the fix for the search is bom

* lint check

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -48,6 +48,22 @@ runs:
       run: |
         mvn -B clean compile package site ${{ inputs.mvn-args }}
 
+    - name: Check and use SBOM file
+      shell: bash
+      run: |
+        if [[ -f "target/bom.json" ]]; then
+          echo "Using existing target/bom.json"
+        else
+          SBOM_FILE=$(find . -path "*/target/classes/META-INF/sbom/application.cdx.json" -type f -print -quit)
+        if [[ -n "$SBOM_FILE" ]]; then
+          echo "target/bom.json not found. Using $SBOM_FILE instead."
+          cp "$SBOM_FILE" target/bom.json
+        else
+          echo "No SBOM file found!" >&2
+          exit 1
+          fi
+        fi
+
     - name: Upload SBOM
       uses: actions/upload-artifact@v4
       with:
